# Generated by Django 2.0.3 on 2018-03-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_parser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLMapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.TextField()),
                ('short_url', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
