# Generated by Django 2.0.3 on 2018-03-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_parser', '0002_auto_20180317_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlmapper',
            name='id',
        ),
        migrations.AlterField(
            model_name='urlmapper',
            name='long_url',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
