# Generated by Django 2.0.3 on 2018-03-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_parser', '0003_auto_20180317_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmapper',
            name='fetch_count',
            field=models.IntegerField(default=0),
        ),
    ]
